# Generated by Django 2.2.6 on 2020-06-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='using_status',
            field=models.CharField(choices=[('Up-to-date', 'Up to date'), ('Out-of-date', 'Out of date')], max_length=20),
        ),
    ]
