# Generated by Django 2.2.5 on 2020-02-04 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20191102_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='about',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
