# Generated by Django 2.2.6 on 2020-03-28 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200328_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='semesters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Semesters'),
        ),
    ]
