# Generated by Django 2.2.6 on 2020-03-28 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200328_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='commoncourses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.CommonCourses'),
        ),
    ]
