# Generated by Django 2.2.6 on 2020-06-13 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articledeleterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledeleterequest',
            name='created_date',
        ),
        migrations.AddField(
            model_name='articledeleterequest',
            name='using_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
