# Generated by Django 2.2.5 on 2020-02-05 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment_approved_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
