# Generated by Django 2.2.6 on 2020-03-28 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200329_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='commoncourses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.CommonCourses'),
        ),
    ]
