# Generated by Django 2.2.6 on 2020-06-13 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200614_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledeleterequest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
