# Generated by Django 2.2.6 on 2020-03-29 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200329_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='about',
            field=models.CharField(max_length=200, verbose_name='What is the subject of Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='commoncourses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.CommonCourses', verbose_name='Common Courses'),
        ),
    ]
