# Generated by Django 2.2.6 on 2020-06-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articledeleterequest_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articledeleterequest',
            options={'verbose_name': 'Article Delete Request Message', 'verbose_name_plural': 'Article Delete Request Messages'},
        ),
        migrations.AddField(
            model_name='articledeleterequest',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='articledeleterequest',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='articledeleterequest',
            name='request_author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='articledeleterequest',
            name='using_status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Read')], default=1),
        ),
    ]
