# Generated by Django 3.1 on 2020-09-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200905_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name="Article's Image Upload"),
        ),
    ]
