# Generated by Django 3.1 on 2020-09-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20200907_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name="Article's Image Upload"),
        ),
    ]
