# Generated by Django 3.1.1 on 2020-09-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200919_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="Article's Image Upload"),
        ),
    ]
