# Generated by Django 2.2.6 on 2020-04-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200430_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_number',
            field=models.CharField(max_length=8, verbose_name='Student Number'),
        ),
    ]
