# Generated by Django 2.2.6 on 2020-05-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200506_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_number',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Student Number:*'),
        ),
    ]
