# Generated by Django 2.2.5 on 2019-09-25 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='author',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='file',
        ),
    ]
