# Generated by Django 2.2.6 on 2020-03-27 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20200327_0346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacultyCommonCourses',
        ),
    ]
