# Generated by Django 2.2.5 on 2019-10-01 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20191002_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Departments'),
        ),
    ]
