# Generated by Django 2.2.6 on 2020-03-27 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_delete_facultycommoncourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Category'),
        ),
    ]
