# Generated by Django 2.2.5 on 2019-10-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_auto_20191002_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='parentid',
        ),
    ]
