# Generated by Django 2.2.6 on 2020-03-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_commoncourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='commoncourses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.CommonCourses'),
        ),
    ]
