# Generated by Django 2.2.6 on 2020-03-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_lessons_commoncourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncourses',
            name='semesters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Semesters'),
        ),
    ]
